services:
  app:
    build: .
    container_name: rust-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - RUST_LOG=${RUST_LOG}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
