services:
  app:
    build: .
    container_name: rust-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - RUST_LOG=${RUST_LOG}
      - CARGO_PKG_VERSION=${CARGO_PKG_VERSION}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
